### ISSUE TITLE
Criar o painel da Recepção

### ISSUE THREAD

**Issue by LiliaMatos** [LiliaMatos/TCC#6]
O painel da recepção deve receber a lista de convites confirmados pela portaria, verificar o campo "LiberadoPortaria"

**Comment by RenanGuedesDePinho** [comment]
Igual ao Painel Portaria (mesmos dados), parâmetro liberadoPortaria tem que ser igual a true pra entrar nesse painel. A data da reunião tem que ser igual ao dia de hoje.
