### ISSUE TITLE
Definir direto no código os tipos de documentos

### ISSUE THREAD

**Issue by RenanGuedesDePinho** [LiliaMatos/TCC#9]

**Comment by LiliaMatos** [comment]
Fontes para pesquisa:
https://www.codeproject.com/Articles/687065/How-to-Use-enum-with-Entity-Framework-5
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constructors
https://pt.stackoverflow.com/questions/178386/atributo-de-classe-com-valores-pr%C3%A9-determinados

**Comment by LiliaMatos** [comment]
Uttilizei  o tipo enum para isso
